import { describe, expect, it } from 'vitest';
import { createBrickModelFromViews, createBrickRelief, createDemoBrickBuild, imageBrickBuildToLdraw } from '../../src/creator/imageBrickModel';

function samplePixels() {
  const width = 12;
  const height = 8;
  const data = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const offset = (y * width + x) * 4;
      const subject = x >= 2 && x <= 9 && y >= 2 && y <= 5;
      data.set(subject ? [201, 26, 9, 255] : [245, 246, 248, 255], offset);
    }
  }
  return { width, height, data };
}

describe('image brick relief generation', () => {
  it('ships with a complete interactive demo model', () => {
    const demo = createDemoBrickBuild();
    expect(demo.bricks.length).toBeGreaterThan(20);
    expect(Math.max(...demo.bricks.map(brick => brick.step))).toBe(demo.steps.length);
  });

  it('quantizes, packs, steps, and inventories a sampled image deterministically', () => {
    const pixels = samplePixels();
    const options = {
      width: 12,
      maxDepth: 3,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'relief' as const,
      bond: 'running' as const,
      brickBudget: 1200,
    };
    const first = createBrickRelief(pixels.data, pixels.width, pixels.height, options, 'red-object');
    const second = createBrickRelief(pixels.data, pixels.width, pixels.height, options, 'red-object');
    expect(second).toEqual(first);
    expect(first.bricks.length).toBeGreaterThan(0);
    expect(new Set(first.bricks.map(brick => brick.id)).size).toBe(first.bricks.length);
    expect(first.bricks.every(brick => [1, 2, 3, 4].includes(brick.width))).toBe(true);
    expect(first.steps.flatMap(step => step.brickIds)).toHaveLength(first.bricks.length);
    expect(Math.max(...first.bricks.map(brick => brick.step))).toBe(first.steps.length);
    expect(first.bom.reduce((sum, item) => sum + item.quantity, 0)).toBe(first.bricks.length);
    expect(first.bom.every(item => item.colorId === 'red')).toBe(true);
  });

  it('exports one LDraw type-1 line per generated brick with step markers', () => {
    const pixels = samplePixels();
    const build = createBrickRelief(pixels.data, pixels.width, pixels.height, {
      width: 12,
      maxDepth: 2,
      maxColors: 4,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'relief',
      bond: 'running',
      brickBudget: 1200,
    }, 'sample');
    const ldraw = imageBrickBuildToLdraw(build);
    expect(ldraw).toContain('0 Generated by Brick Atlas Image Studio');
    expect(ldraw.split('\n').filter(line => line.startsWith('1 '))).toHaveLength(build.bricks.length);
    expect(ldraw).toContain('0 STEP');
  });

  it('fuses three silhouettes into a bounded hollow sculpture', () => {
    const pixels = samplePixels();
    const view = { data: pixels.data, width: pixels.width, height: pixels.height };
    const build = createBrickModelFromViews({ front: view, top: view, side: view }, {
      width: 12,
      maxDepth: 4,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'hollow',
      bond: 'reinforced',
      brickBudget: 1200,
    }, 'three-view');
    expect(build.viewCount).toBe(3);
    expect(build.method).toBe('hollow');
    expect(build.bond).toBe('reinforced');
    expect(build.maxDepth).toBeGreaterThan(0);
    expect(build.maxDepth).toBeLessThanOrEqual(8);
    expect(build.bricks.length).toBeGreaterThan(0);
    expect(build.bricks.every(brick => brick.x >= -6 && brick.x <= 6)).toBe(true);
    expect(build.steps[0].layer).toBe(0);
    const occupied = new Set<string>();
    for (const brick of build.bricks) {
      const start = brick.x - brick.width / 2;
      for (let stud = 0; stud < brick.width; stud++) {
        const key = `${start + stud}:${brick.y}:${brick.z}`;
        expect(occupied.has(key)).toBe(false);
        occupied.add(key);
      }
    }
  });
});
