import { describe, expect, it } from 'vitest';
import {
  createBrickModelFromViews, createBrickRelief, createEmptyBrickBuild,
  imageBrickBuildToLdraw,
} from '../../src/creator/imageBrickModel';

function samplePixels() {
  const width = 12;
  const height = 8;
  const data = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const offset = (y * width + x) * 4;
      const subject = x >= 2 && x <= 9 && y >= 2 && y <= 5;
      data.set(subject ? [201, 26, 9, 255] : [245, 246, 248, 255], offset);
    }
  }
  return { width, height, data };
}

describe('image brick relief generation', () => {
  it('starts Create without a baked-in vehicle', () => {
    expect(createEmptyBrickBuild()).toMatchObject({
      bricks: [],
      steps: [],
      viewCount: 0,
      reconstruction: 'empty',
    });
  });

  it('quantizes, packs, steps, and inventories a sampled image deterministically', () => {
    const pixels = samplePixels();
    const options = {
      width: 12,
      maxDepth: 3,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'relief' as const,
      bond: 'running' as const,
      brickBudget: 1200,
    };
    const first = createBrickRelief(pixels.data, pixels.width, pixels.height, options, 'red-object');
    const second = createBrickRelief(pixels.data, pixels.width, pixels.height, options, 'red-object');
    expect(second).toEqual(first);
    expect(first.bricks.length).toBeGreaterThan(0);
    expect(new Set(first.bricks.map(brick => brick.id)).size).toBe(first.bricks.length);
    expect(first.bricks.every(brick => [1, 2, 3, 4].includes(brick.width))).toBe(true);
    expect(first.steps.flatMap(step => step.brickIds)).toHaveLength(first.bricks.length);
    expect(Math.max(...first.bricks.map(brick => brick.step))).toBe(first.steps.length);
    expect(first.bom.reduce((sum, item) => sum + item.quantity, 0)).toBe(first.bricks.length);
    expect(first.bom.every(item => item.colorId === 'red')).toBe(true);
  });

  it('exports one LDraw type-1 line per generated brick with step markers', () => {
    const pixels = samplePixels();
    const build = createBrickRelief(pixels.data, pixels.width, pixels.height, {
      width: 12,
      maxDepth: 2,
      maxColors: 4,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'relief',
      bond: 'running',
      brickBudget: 1200,
    }, 'sample');
    const ldraw = imageBrickBuildToLdraw(build);
    expect(ldraw).toContain('0 Generated by Brick Atlas Image Studio');
    expect(ldraw.split('\n').filter(line => line.startsWith('1 '))).toHaveLength(build.bricks.length);
    expect(ldraw).toContain('0 STEP');
  });

  it('fuses three silhouettes into a bounded hollow sculpture', () => {
    const pixels = samplePixels();
    const view = { data: pixels.data, width: pixels.width, height: pixels.height };
    const build = createBrickModelFromViews({ front: view, left: view, back: view }, {
      width: 12,
      maxDepth: 4,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'hollow',
      bond: 'reinforced',
      brickBudget: 1200,
    }, 'three-view');
    expect(build.viewCount).toBe(3);
    expect(build.method).toBe('hollow');
    expect(build.bond).toBe('reinforced');
    expect(build.maxDepth).toBeGreaterThan(0);
    expect(build.maxDepth).toBeLessThanOrEqual(8);
    expect(build.bricks.length).toBeGreaterThan(0);
    expect(build.bricks.every(brick => brick.x >= -6 && brick.x <= 6)).toBe(true);
    expect(build.steps[0].layer).toBe(0);
    const occupied = new Set<string>();
    for (const brick of build.bricks) {
      const start = brick.x - brick.width / 2;
      for (let stud = 0; stud < brick.width; stud++) {
        const key = `${start + stud}:${brick.y}:${brick.z}`;
        expect(occupied.has(key)).toBe(false);
        occupied.add(key);
      }
    }
  });

  it('turns one real-photo silhouette into a centered volumetric sculpture', () => {
    const pixels = samplePixels();
    const depth = new Float32Array(pixels.width * pixels.height);
    for (let y = 0; y < pixels.height; y++) {
      for (let x = 0; x < pixels.width; x++) {
        depth[y * pixels.width + x] = x / (pixels.width - 1);
      }
    }
    const build = createBrickModelFromViews({
      front: pixels,
      frontDepth: { data: depth, width: pixels.width, height: pixels.height },
    }, {
      width: 12,
      maxDepth: 8,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'solid',
      bond: 'running',
      brickBudget: 1200,
    }, 'single-photo');
    expect(build.reconstruction).toBe('depth-ai');
    expect(build.maxDepth).toBeGreaterThan(2);
    expect(new Set(build.bricks.map(brick => brick.z)).size).toBeGreaterThan(2);
    expect(build.bricks.some(brick => (brick.depth ?? 1) === 2)).toBe(true);
    const shell = createBrickModelFromViews({
      front: pixels,
      frontDepth: { data: depth, width: pixels.width, height: pixels.height },
    }, {
      width: 12,
      maxDepth: 8,
      maxColors: 6,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'hollow',
      bond: 'running',
      brickBudget: 1200,
    }, 'single-photo-shell');
    expect(shell.bricks.length).toBeLessThan(build.bricks.length);
    expect(new Set(shell.bricks.map(brick => brick.z)).size).toBeGreaterThan(2);
  });

  it('keeps fused colors within the requested palette size and offsets running bonds', () => {
    const data = new Uint8ClampedArray(12 * 4 * 4);
    for (let i = 0; i < 48; i++) data.set([i * 37 % 256, i * 71 % 256, i * 113 % 256, 255], i * 4);
    const options = { width: 12, maxDepth: 1, maxColors: 4, removeBackground: false, backgroundThreshold: 12, method: 'relief' as const, bond: 'running' as const, brickBudget: 500 };
    const build = createBrickRelief(data, 12, 4, options);
    expect(new Set(build.bricks.map(brick => brick.colorCode)).size).toBeLessThanOrEqual(4);
    for (let i = 0; i < 48; i++) data.set([200, 20, 10, 255], i * 4);
    const running = createBrickRelief(data, 12, 4, options);
    const stacked = createBrickRelief(data, 12, 4, { ...options, bond: 'stacked' });
    expect(running.bricks.map(brick => brick.x)).not.toEqual(stacked.bricks.map(brick => brick.x));
  });

  it('exports brick tops at 24 LDU per layer without injecting metadata lines', () => {
    const pixels = samplePixels();
    const build = createBrickRelief(pixels.data, pixels.width, pixels.height, {
      width: pixels.width,
      maxDepth: 2,
      maxColors: 4,
      removeBackground: true,
      backgroundThreshold: 12,
      method: 'relief',
      bond: 'running',
      brickBudget: 1200,
    });
    build.name = 'demo\n1 injected';
    build.bricks = [
      { ...build.bricks[0], x: 0, z: 0, y: 0.6, step: 1 },
      { ...build.bricks[0], x: 0, z: 0, y: 1.8, step: 2 },
    ];
    const lines = imageBrickBuildToLdraw(build).split('\n').filter(line => line.startsWith('1 '));
    expect(lines).toHaveLength(2);
    expect(lines.map(line => Number(line.split(' ')[3]))).toEqual([-24, -48]);
  });
});
